\doxysection{ph\+::Runtime\+Exception Class Reference}
\hypertarget{classph_1_1_runtime_exception}{}\label{classph_1_1_runtime_exception}\index{ph::RuntimeException@{ph::RuntimeException}}


General exception thrown on runtime error.  




{\ttfamily \#include $<$exception.\+h$>$}

Inheritance diagram for ph\+::Runtime\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.064516cm]{d2/dd1/classph_1_1_runtime_exception}
\end{center}
\end{figure}
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\Hypertarget{classph_1_1_runtime_exception_a129b04101fbe5ba1d181be8cc157eac4}\label{classph_1_1_runtime_exception_a129b04101fbe5ba1d181be8cc157eac4} 
{\bfseries Runtime\+Exception} (const std\+::string \&message)
\item 
\Hypertarget{classph_1_1_runtime_exception_a0463e3abb5f1e5e8b339d6e2f7f82a32}\label{classph_1_1_runtime_exception_a0463e3abb5f1e5e8b339d6e2f7f82a32} 
{\bfseries Runtime\+Exception} (const char \texorpdfstring{$\ast$}{*}message)
\item 
\Hypertarget{classph_1_1_runtime_exception_a1d68d40f02f2d4969a7f739da22f32ec}\label{classph_1_1_runtime_exception_a1d68d40f02f2d4969a7f739da22f32ec} 
virtual std\+::string {\bfseries what\+Str} () const
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
General exception thrown on runtime error. 

The documentation for this class was generated from the following files\+:\begin{DoxyCompactItemize}
\item 
Source/\+Utility/exception.\+h\item 
Source/\+Utility/exception.\+cpp\end{DoxyCompactItemize}
